### ISSUE TITLE
license is missing

### ISSUE THREAD

**Issue by bjo81** [jinglemansweep/lcdproc#8]
Hi, 

I packaged lcdproc for the Arch Linux User Repo, so I wanted to know under which license you release it.

**Comment by jinglemansweep** [comment]
It's BSD licensed. I'll add a LICENCE file.

**Comment by ssokolow** [comment]
Probably also a good idea to add the license to your `setup.py` via the `license` and `classifiers` arguments:

https://packaging.python.org/en/latest/distributing.html#license
